trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: DevOp  # Contains DOCKERHUB_USERNAME, DOCKERHUB_PASSWORD, RENDER_API_KEY, RENDER_SERVICE_ID

steps:

- script: |
    echo "Downloading Render CLI..."
    curl -L https://github.com/render/render-cli/releases/latest/download/render-linux-amd64 -o render

    echo "Making Render CLI executable..."
    chmod +x render

    echo "Moving Render CLI to /usr/local/bin..."
    sudo mv render /usr/local/bin/render

    echo "Verifying Render CLI installation..."
    render --version
  displayName: 'Install Render CLI'

# Step 2: Format Code Before Building
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'io.spring.javaformat:spring-javaformat-maven-plugin:0.0.27:apply'
    options: '-DskipTests'
  displayName: 'Format Code with Maven'

# Step 3: Run Tests and SonarQube Analysis
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: '5.1.0.4751'
    options: '-Dsonar.token=$(SONAR_TOKEN)'
  displayName: 'Run Tests & SonarQube Analysis'

# Step 4: Publish Test Results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Tests for Petclinic'
  displayName: 'Publish Test Results'

# Step 5: Docker Hub Authentication
- script: |
    echo "Logging in to Docker Hub..."
    echo $(DOCKERHUB_PASSWORD) | docker login --username $(DOCKERHUB_USERNAME) --password-stdin
  displayName: 'Login to Docker Hub'

# Step 6: Build and Push Docker Image
- script: |
    IMAGE_NAME=$(DOCKERHUB_USERNAME)/petclinic-app2:latest
    echo "Building Docker image: $IMAGE_NAME"
    docker buildx build --provenance=false -t $IMAGE_NAME .

    echo "Pushing Docker image to Docker Hub..."
    docker push $IMAGE_NAME
  displayName: 'Build & Push Docker Image'

# Step 7: Trigger Deployment on Render
- script: |
    echo "Triggering deployment on Render..."
    render deploys create $(RENDER_SERVICE_ID) \
      --image $(DOCKERHUB_USERNAME)/petclinic-app2:latest \
      --wait
    echo "Deployment triggered successfully!"
  displayName: 'Trigger Deployment on Render'

# Step 8: Verify Deployment Status
- script: |
    echo "Checking deployment status on Render..."
    curl -X GET \
      https://api.render.com/v1/services/$(RENDER_SERVICE_ID) \
      -H "Authorization: Bearer $(RENDER_API_KEY)"
    echo "Visit your Render dashboard for deployment status."
  displayName: 'Verify Render Deployment'
